### ISSUE TITLE
Undefined name 'BLACK' in go.py

### ISSUE THREAD

**Issue by cclauss** [EmbersArc/gym#2]
flake8 testing of https://github.com/EmbersArc/gym on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./envs/board_game/go.py:108:60: F821 undefined name 'BLACK'
    curr_state = GoState(pachi_py.CreateBoard(board_size), BLACK)
                                                           ^
./envs/board_game/go.py:111:53: F821 undefined name 'BLACK'
        a = (black_policy_fn if curr_state.color == BLACK else white_policy_fn)(curr_state, prev_state, prev_action)
                                                    ^
2     F821 undefined name 'BLACK'
```

**Comment by EmbersArc** [comment]
Not part of my implementation, only important file is https://github.com/EmbersArc/gym/blob/master/envs/box2d/rocket_lander.py and the init functions. See https://github.com/openai/gym#environments
