### ISSUE TITLE
AssertionError: Failed on kwargs

### ISSUE THREAD

**Issue by mymultiverse** [EmbersArc/gym#3]
When is try to make env with gym I get:-

    pybox2d/library/Box2D/Box2D.py", line 158, in _init_kwargs
    % (self.__class__.__name__, key, ex))
    AssertionError: Failed on kwargs for b2PolygonShape.vertices: count >= 3

**Comment by EmbersArc** [comment]
That means that one polygon is invalid... is it in RocketLander-v0?
Did you change anything?

**Comment by mymultiverse** [comment]
Yes it is in RocketLander-v0. As I already have box2d env other than RocketLander so I only took rocket_laner from your repo and I added RocketLander in init.py file.
I am trying to run this programme

    import gym
    env = gym.make("RocketLander-v0")
    env.reset()
    for _ in range(1000):
	    env.render()
	    action = env.action_space.sample()
	    obs, reward, done, info = env.step(action)
	    print("Action: {} Observations Size:{} score: {}".format(action,obs.shape,reward))
	    if done:
 		    break

**Comment by EmbersArc** [comment]
Works fine for me. I'm using Python 3.6.
I updated the gym files, maybe try again with those.

**Comment by mymultiverse** [comment]
So is it problem-related to python version as I am using Python 2.7 with anaconda? 
I am able to run LunarLander-v2 successfully.

**Comment by EmbersArc** [comment]
Most likely. Try with a 3.6 environment.

**Comment by mymultiverse** [comment]
when I run with python3  

    AttributeError: module 'Box2D._Box2D' has no attribute 'RAND_LIMIT'

**Comment by abhiksingla** [comment]
If you have not installed the complete gym package (i.e using gym[all]), then install "Box2D-kengz" additionally. Use `pip install Box2D-kengz` or `pip3 install Box2D-kengz`.

**Comment by mymultiverse** [comment]
I installed Box2D-kengz but getting same attribute error for both python environments.

**Comment by timelong** [comment]
**I had the same problem, but I have solved it!**

In the line 80 of the  `envs/box2d/rocket_lander.py`, we can see that `W =   VIEWPORT_W  / VIEWPORT_H * H`. From the line 77 and 78, we known that `VIEWPORT_W = 1008` (it's an integer) and `VIEWPORT_H = 1440` (it's also an integer). So `W is 0` because `VIEWPORT_W` is less than `VIEWPORT_H`.

I modified this line in this way `W = VIEWPORT_W * 1.0 / ( VIEWPORT_H * 1.0 ) * H`, then the problem was solved !

**Comment by EmbersArc** [comment]
@timelong Any idea why this is only a problem for some people? Integer division in python usually doesn't lead to rounded down results.
`print(1008/1440)` returns `0.7`

**Comment by mymultiverse** [comment]
I am able to run the environment with Python 2.7  but I am getting a dark background. 
![selection_071](https://user-images.githubusercontent.com/14858165/37338019-7c5b7d0a-26f9-11e8-928e-6a7a4dd570ed.png)

**Comment by EmbersArc** [comment]
Again, because of the RGB calculation, it does integer division which results in 0.
I'll adjust the code but use Python 3.6 if possible.

**Comment by mymultiverse** [comment]
It is working fine with Python 3.6 but in the environment window,
![screenshot from 2018-04-04 14-44-12](https://user-images.githubusercontent.com/14858165/38290753-c0263816-3817-11e8-9785-f4385c34dd46.png)
 I can not see the landing platform.

**Comment by mymultiverse** [comment]
Need to adjust the VIEWPORT parameters according to the screen to see the environment window completely.
