### ISSUE TITLE
Can you share the model that has been trained well so I can get the same result like the gif shows in the README?

### ISSUE THREAD

**Issue by timelong** [EmbersArc/gym#5]
I can  run the PPO.py, and can see the process of training. But after training for about a couple of hours, my computer(the GPU is GeForce 1060) would  breakdown.  

So, I just want to test the model you have trained well. Could you share it ? Thanks!

**Comment by EmbersArc** [comment]
Model is right here: https://github.com/EmbersArc/PPO
(in the folder working model)

**Comment by airqualityanthony** [comment]
how do you go about implementing this model? I'm playing around with stable-baselines models at the moment, and not having any good luck with them - reward system seems to not play well.
